# Generated by Django 5.1.3 on 2024-12-10 16:18

import community.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CommunityPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("parent", models.CharField(max_length=255)),
                ("author", models.CharField(max_length=255)),
                ("content_text", models.TextField()),
                (
                    "content_image",
                    models.ImageField(
                        upload_to=community.models.get_community_image_post_directory
                    ),
                ),
                ("likes", models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="CommunityPostComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author", models.CharField(max_length=255)),
                ("content_text", models.TextField()),
                ("likes", models.BigIntegerField()),
            ],
        ),
    ]
