# Generated by Django 5.1.3 on 2024-12-10 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="communitypostcomment",
            name="post",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="community.communitypost",
            ),
            preserve_default=False,
        ),
    ]
