# Generated by Django 5.1.3 on 2024-12-10 16:33

import community.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0002_communitypostcomment_post"),
    ]

    operations = [
        migrations.AlterField(
            model_name="communitypost",
            name="content_image",
            field=models.ImageField(
                default=None,
                upload_to=community.models.get_community_image_post_directory,
            ),
        ),
    ]
