# Generated by Django 5.1.3 on 2024-12-15 10:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0003_alter_communitypost_content_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="communitypostcomment",
            name="created_at",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
