# Generated by Django 5.1.3 on 2024-12-18 19:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FoodTrack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "food_type",
                    models.CharField(
                        choices=[
                            ("Breakfast", "Breakfast"),
                            ("Lunch", "Lunch"),
                            ("Dinner", "Dinner"),
                            ("Dessert", "Dessert"),
                        ],
                        max_length=20,
                    ),
                ),
                ("food_name", models.CharField(max_length=100)),
                ("calorie", models.IntegerField()),
                ("sugar", models.FloatField()),
                ("fiber", models.FloatField()),
                ("protein", models.FloatField()),
                ("time", models.DateTimeField(default=django.utils.timezone.now)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-time"],
            },
        ),
    ]
